// 国家名 → 旗帜 emoji（football-data.org 的队名拼写）。未知则返回 ⚽。
const FLAGS: Record<string, string> = {
  "United States": "🇺🇸",
  USA: "🇺🇸",
  Canada: "🇨🇦",
  Mexico: "🇲🇽",
  Brazil: "🇧🇷",
  Argentina: "🇦🇷",
  France: "🇫🇷",
  Spain: "🇪🇸",
  Germany: "🇩🇪",
  Portugal: "🇵🇹",
  England: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  Netherlands: "🇳🇱",
  Belgium: "🇧🇪",
  Italy: "🇮🇹",
  Croatia: "🇭🇷",
  Uruguay: "🇺🇾",
  Colombia: "🇨🇴",
  Japan: "🇯🇵",
  "South Korea": "🇰🇷",
  Australia: "🇦🇺",
  Morocco: "🇲🇦",
  Senegal: "🇸🇳",
  Switzerland: "🇨🇭",
  Denmark: "🇩🇰",
  Poland: "🇵🇱",
  Serbia: "🇷🇸",
  "South Africa": "🇿🇦",
  Czechia: "🇨🇿",
  "Bosnia-Herzegovina": "🇧🇦",
  Ecuador: "🇪🇨",
  Mexico_: "🇲🇽",
  Ghana: "🇬🇭",
  Nigeria: "🇳🇬",
  Cameroon: "🇨🇲",
  Tunisia: "🇹🇳",
  Algeria: "🇩🇿",
  Egypt: "🇪🇬",
  "Ivory Coast": "🇨🇮",
  "Côte d'Ivoire": "🇨🇮",
  "Saudi Arabia": "🇸🇦",
  Iran: "🇮🇷",
  Qatar: "🇶🇦",
  "United Arab Emirates": "🇦🇪",
  Peru: "🇵🇪",
  Chile: "🇨🇱",
  Paraguay: "🇵🇾",
  Austria: "🇦🇹",
  "Czech Republic": "🇨🇿",
  Norway: "🇳🇴",
  Sweden: "🇸🇪",
  Turkey: "🇹🇷",
  Türkiye: "🇹🇷",
  Scotland: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  Wales: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  Greece: "🇬🇷",
  "New Zealand": "🇳🇿",
  "Costa Rica": "🇨🇷",
  Panama: "🇵🇦",
  Jamaica: "🇯🇲",
};

export function countryFlag(name: string): string {
  return FLAGS[name] ?? "⚽";
}
